name: Explode the Bomb

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Configure Git author
      run: |
        git config user.name "Krauzy"
        git config user.email "30305307+Krauzy@users.noreply.github.com"

    - name: Run yarn start
      run: yarn start
